#cloud-config


# Update system
package_update: true
package_upgrade: true

# Configure time zone
timezone: 'US/East'

#Add hostname
hostname: lab2

# Creates admin1 user
users: 
  - name: admin1
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: home/admin1
    ssh_authorized_keys: 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCN16qjaXPU8mYKkGAg4qEWuMqwe9Ax0HGayd7dKIAoVXSe2cFlzsxp1LtAi6m7wrW0uybsf9nLz82sM95ofAZEyCotc/695cQ8QfvTYGmSNRq1dslz7i4ooOXiH0DOL58sTxonRDloy431t0lQWOxwmqhHYEcWsaA+W1P1HxfRR7/OChpNuc6muhrfctn2AVmY7noJRqutrXxUyNg/9orJAAyNUu6gu09amMVOpV/3QGHEQaDjXWPEo0D7b844epZMsDNs6u9w4KWIMJunP4tH9eBnka0Gj8E+YKJftt1zMfpkLUfzXiuWjks9l7PbtLHOS8jVue3sbAjbma72JeJZ
  
  #Install packages
packages:
  - cowsay
  - sl	
  #Run commands
runcmd:
  - echo "Hello from our group!"
  - /usr/bin/lshw 
  - cowsay Hello from our group! 
