[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CNIT 48101 Lab Documentation"
authors = [{name = "Jacob Bauer & Nick Kuenning", email = "bauerja@purdue.edu"}]
dynamic = ["version", "description"]
